-- =============================================================================
-- Data Load Script - Load CSVs from @DATAFILES stage into tables
-- =============================================================================
-- Prerequisites:
--   1. Run ddl/create_tables.sql to create database, schema, stage, and tables
--   2. Upload CSV files to the DATAFILES stage using PUT or the Snowsight UI
--      e.g. PUT 'file:///path/to/output/site.csv' @DATAFILES/SITE/ OVERWRITE=TRUE;
-- =============================================================================

USE ROLE ACCOOUNTADMIN;
USE DATABASE HS_WORKSHOP;
USE SCHEMA RAW;

-- -----------------------------------------------------------------------------
-- Load tables in FK dependency order
-- -----------------------------------------------------------------------------

COPY INTO SITE 
FROM @DATAFILES/site.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO BUILDING 
FROM @DATAFILES/building.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO ASSET 
FROM @DATAFILES/asset.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO PERSON 
FROM @DATAFILES/person.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO CONTRACTOR 
FROM @DATAFILES/contractor.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO SITE_CONTRACTOR 
FROM @DATAFILES/site_contractor.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO HAZARD 
FROM @DATAFILES/hazard.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO INCIDENT 
FROM @DATAFILES/incident.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO RISK_ASSESSMENT 
FROM @DATAFILES/risk_assessment.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO INSPECTION 
FROM @DATAFILES/inspection.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

COPY INTO ACTION_ITEM 
FROM @DATAFILES/action_item.csv
FILE_FORMAT = CSV_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

-- -----------------------------------------------------------------------------
-- Verification: Row counts for all tables
-- -----------------------------------------------------------------------------

SELECT 'SITE' AS table_name, COUNT(*) AS row_count FROM SITE
UNION ALL
SELECT 'BUILDING', COUNT(*) FROM BUILDING
UNION ALL
SELECT 'ASSET', COUNT(*) FROM ASSET
UNION ALL
SELECT 'PERSON', COUNT(*) FROM PERSON
UNION ALL
SELECT 'CONTRACTOR', COUNT(*) FROM CONTRACTOR
UNION ALL
SELECT 'SITE_CONTRACTOR', COUNT(*) FROM SITE_CONTRACTOR
UNION ALL
SELECT 'HAZARD', COUNT(*) FROM HAZARD
UNION ALL
SELECT 'INCIDENT', COUNT(*) FROM INCIDENT
UNION ALL
SELECT 'RISK_ASSESSMENT', COUNT(*) FROM RISK_ASSESSMENT
UNION ALL
SELECT 'INSPECTION', COUNT(*) FROM INSPECTION
UNION ALL
SELECT 'ACTION_ITEM', COUNT(*) FROM ACTION_ITEM
ORDER BY table_name;
